Parameters:
  SagemakerCodeRepo:
    Type: String
    Description: Github Repository for loading into the Sagemaker Jupyter environment
    Default: https://github.com/stevengillard/amazon-asdi.git

  SagemakerNotebookInstance:
    Type: String
    Description: Sagemaker Notebook instance type
    AllowedValues:
      - ml.t3.medium
      - ml.t3.large
      - ml.t3.xlarge
      - ml.t3.2xlarge
      - ml.m5.xlarge
      - ml.m5.2xlarge
      - ml.m5.4xlarge
    Default: ml.t3.large

  DaskImage:
    Type: String
    Default: public.ecr.aws/j7x5r0l2/aws-dask-workshop:latest
    Description: Container image to use for the Dask workers

  DaskWorkerCPU:
    Type: String
    Default: '1024'
    Description: CPU units to assign to dask workers (1024 = 1 vCPU)

  DaskWorkerMemory:
    Type: String
    Default: '8192'
    Description: Memory in MiB for dask workers

  DaskWorkerSpotPricing:
    Type: String
    Default: 'YES'
    Description: Use Fargate spot pricing for dask workers, to save money (workers may be terminated)
    AllowedValues:
      - 'YES'
      - 'NO'

  DaskDashboardPort:
    Type: Number
    Default: 80
    Description: Port number to use for dask dashboard HTTP interface

  AllowedIPRange:
    Type: String
    Default: 0.0.0.0/0
    Description: IP range to allow access to dask dashboard

Conditions:
  DaskWorkerSpotPricingCondition: !Equals [!Ref DaskWorkerSpotPricing, 'YES']

Resources:
  DaskVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.10.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: dask-fargate/MyVpc
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.10.0.0/18
      VpcId:
        Ref: DaskVpc
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: dask-fargate/PublicSubnet1
  PublicSubnet1RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: DaskVpc
      Tags:
        - Key: Name
          Value: dask-fargate/MyVpc/PublicSubnet1
  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PublicSubnet1RouteTable
      SubnetId:
        Ref: PublicSubnet1
  PublicSubnet1DefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: PublicSubnet1RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway
    DependsOn:
      - VPCGatewayA
  PublicSubnet1EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: dask-fargate/MyVpc/PublicSubnet1
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: dask-fargate/MyVpc
  VPCGatewayA:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: DaskVpc
      InternetGatewayId:
        Ref: InternetGateway
  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt PublicSubnet1EIP.AllocationId
      SubnetId: !Ref PublicSubnet1
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.10.64.0/18
      VpcId:
        Ref: DaskVpc
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      Tags:
        - Key: Name
          Value: dask-fargate/PrivateSubnet1
  PrivateSubnet1RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: DaskVpc
      Tags:
        - Key: Name
          Value: dask-fargate/MyVpc/PrivateSubnet1
  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateSubnet1RouteTable
      SubnetId:
        Ref: PrivateSubnet1
  PrivateSubnet1DefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: PrivateSubnet1RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: NATGateway
  PrivateSubnetS3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      RouteTableIds:
        - !Ref PrivateSubnet1RouteTable
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcId: !Ref DaskVpc

  LogGroupScheduler:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/${AWS::StackName}/dask/scheduler
      RetentionInDays: 3
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
  LogGroupWorker:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/${AWS::StackName}/dask/worker
      RetentionInDays: 3
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete

  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
        Version: "2012-10-17"
  ECSExecutionRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - ecr:BatchCheckLayerAvailability
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:GetAuthorizationToken
            Effect: Allow
            Resource: "*"
          - Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - LogGroupScheduler
                - Arn
          - Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - LogGroupWorker
                - Arn
        Version: "2012-10-17"
      PolicyName: ECSExecutionRolePolicy
      Roles:
        - Ref: ECSExecutionRole
  DaskCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Join ["-", [!Ref "AWS::StackName", "Fargate-Dask-Cluster"]]
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
        - CapacityProvider: FARGATE_SPOT
          Weight: 0

  DaskClusterPrivateNS:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Name: local-dask
      Vpc:
        Ref: DaskVpc

  SchedulerDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Command:
            - dask-scheduler
            - --dashboard
            - --dashboard-address
            - !Ref DaskDashboardPort
          Cpu: 4096
          Essential: true
          Image: !Ref DaskImage
          LogConfiguration: 
            LogDriver: awslogs
            Options:
              awslogs-group:
                Ref: LogGroupScheduler
              awslogs-stream-prefix: ecs
              awslogs-region:
                Ref: AWS::Region
          Memory: 30720
          MemoryReservation: 30720
          Name: Dask
      Cpu: "4096"
      ExecutionRoleArn:
        Fn::GetAtt:
          - ECSExecutionRole
          - Arn
      Family: Dask-Scheduler
      Memory: "30720"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      TaskRoleArn:
        Fn::GetAtt:
          - ECSExecutionRole
          - Arn
  WorkerDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Command:
            - dask-worker
            - dask-scheduler.local-dask:8786
            - --memory-limit
            - '7000MB'
            - --worker-port
            - '9000'
            - --no-nanny
            - --no-dashboard
            - --death-timeout
            - '30'
            - --nthreads
            - '2'
            - --nprocs
            - '1'
          Cpu: !Ref DaskWorkerCPU
          Essential: true
          Image: !Ref DaskImage
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:
                Ref: LogGroupWorker
              awslogs-stream-prefix: ecs
              awslogs-region:
                Ref: AWS::Region
          Memory: !Ref DaskWorkerMemory
          MemoryReservation: !Ref DaskWorkerMemory
          Name: Dask
      Cpu: !Ref DaskWorkerCPU
      ExecutionRoleArn:
        Fn::GetAtt:
          - ECSExecutionRole
          - Arn
      Family: Dask-Worker
      Memory: !Ref DaskWorkerMemory
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      TaskRoleArn:
        Fn::GetAtt:
          - ECSExecutionRole
          - Arn

  DaskSchedulerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable Scheduler ports access
      GroupName: DaskSchedulerSecurityGroup
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      SecurityGroupIngress:
        - CidrIp: !Ref AllowedIPRange
          Description: Allow access to the dask dashboard
          FromPort: !Ref DaskDashboardPort
          IpProtocol: tcp
          ToPort: !Ref DaskDashboardPort
        - SourceSecurityGroupId: !GetAtt NotebookSecurityGroup.GroupId
          Description: Allow access from SageMaker notebook
          FromPort: 8786
          IpProtocol: tcp
          ToPort: 8789
      VpcId: !Ref DaskVpc

  NotebookSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access to SageMaker notebook instance
      GroupName: NotebookSecurityGroup
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: '-1'
      VpcId: !Ref DaskVpc

  DaskWorkerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Restrict connectivity to dask workers
      GroupName: DaskWorkerSecurityGroup
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: '-1'
      SecurityGroupIngress:
        - SourceSecurityGroupId: !GetAtt DaskSchedulerSecurityGroup.GroupId
          Description: Allow full access from dask scheduler
          IpProtocol: '-1'
        - SourceSecurityGroupId: !GetAtt NotebookSecurityGroup.GroupId
          Description: Allow full access from the notebook
          IpProtocol: '-1'
      VpcId: !Ref DaskVpc

  DaskWorkerToWorkerIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Allow dask workers to communicate freely with each other
      GroupId: !GetAtt DaskWorkerSecurityGroup.GroupId
      SourceSecurityGroupId: !GetAtt DaskWorkerSecurityGroup.GroupId
      IpProtocol: '-1'

  DaskWorkerToSchedulerIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Allow dask workers to communicate with the scheduler
      GroupId: !GetAtt DaskSchedulerSecurityGroup.GroupId
      SourceSecurityGroupId: !GetAtt DaskWorkerSecurityGroup.GroupId
      IpProtocol: '-1'

  DaskSchedulerService:
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Ref: DaskCluster
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DesiredCount: 1
      EnableECSManagedTags: false
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - Fn::GetAtt:
                - DaskSchedulerSecurityGroup
                - GroupId
          Subnets:
            - Ref: PublicSubnet1
      ServiceName: Dask-Scheduler
      ServiceRegistries:
        - RegistryArn:
            Fn::GetAtt:
              - DaskSchedulerServiceDiscovery
              - Arn
      TaskDefinition:
        Ref: SchedulerDefinition

  DaskSchedulerServiceDiscovery:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      DnsConfig:
        DnsRecords:
          - TTL: 5
            Type: A
        NamespaceId:
          Fn::GetAtt:
            - DaskClusterPrivateNS
            - Id
        RoutingPolicy: MULTIVALUE
      HealthCheckCustomConfig:
        FailureThreshold: 1
      Name: Dask-Scheduler
      NamespaceId:
        Fn::GetAtt:
          - DaskClusterPrivateNS
          - Id

  DaskWorkerService:
    Type: AWS::ECS::Service
    Properties:
      CapacityProviderStrategy:
        - CapacityProvider:
            Fn::If:
              - DaskWorkerSpotPricingCondition
              - FARGATE_SPOT
              - FARGATE
          Weight: 1
      Cluster:
        Ref: DaskCluster
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DesiredCount: 0
      EnableECSManagedTags: false
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - Fn::GetAtt:
                - DaskWorkerSecurityGroup
                - GroupId
          Subnets:
            - Ref: PrivateSubnet1
      ServiceName: Dask-Worker
      TaskDefinition:
        Ref: WorkerDefinition

  NotebookWaitHandle:
    Type: AWS::CloudFormation::WaitConditionHandle

  NotebookWaitCondition:
    Type: AWS::CloudFormation::WaitCondition
    Properties:
      Count: 1
      Handle: !Ref NotebookWaitHandle
      Timeout: "900"

  SagemakerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
        Version: "2012-10-17"
  SagemakerPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:*
              - ecs:*
              - logs:*
              - ec2:DescribeNetworkInterfaces
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: notebookAccessPolicy
      Roles:
        - Ref: SagemakerRole

  NotebookLifecycleConfig:
    Type: AWS::SageMaker::NotebookInstanceLifecycleConfig
    Properties:
      OnCreate:
      - Content:
          Fn::Base64:
            Fn::Sub: |
              #!/bin/sh
              set -e
              WORKING_DIR=/home/ec2-user/SageMaker/custom-miniconda

              cat > /home/ec2-user/create.sh << EOF
              #!/bin/bash

              echo "\$(date) Installing custom miniconda into $WORKING_DIR"
              mkdir -p "$WORKING_DIR"
              wget -q https://repo.anaconda.com/miniconda/Miniconda3-py39_4.12.0-Linux-x86_64.sh -O "$WORKING_DIR/miniconda.sh"
              bash "$WORKING_DIR/miniconda.sh" -b -u -p "$WORKING_DIR/miniconda"

              echo "\$(date) Creating daskpy3 conda environment"
              source "$WORKING_DIR/miniconda/bin/activate"
              conda create --yes --name daskpy3 python="3.10.4"
              conda activate daskpy3
              echo "python ==3.10.4" >> $WORKING_DIR/miniconda/envs/daskpy3/conda-meta/pinned

              echo "\$(date) Installing packages using micromamba"
              conda install -c conda-forge micromamba -y 
              micromamba install -c conda-forge basemap nodejs ipywidgets==7.7.1 -y 

              echo "\$(date) Installing packages using pip"
              pip install botocore==1.27.59 aiobotocore==2.4.0 zarr==2.12.0 rechunker==0.5.0 ipykernel==6.15.2 matplotlib==3.5.3 boto3==1.24.59 dask==2022.9.0 distributed==2022.9.0 tornado==6.1 cloudpickle==2.1.0 msgpack==1.0.4 blosc==1.10.6 numpy==1.23.2 pandas==1.4.4 lz4==4.0.0 netcdf4==1.6.0 xarray==2022.6.0 bokeh==2.4.3 s3fs==2022.8.2 fsspec==2022.8.2 h5netcdf==1.0.2 h5py==3.7.0 intake-esm==2021.8.17 intake==0.6.6

              echo "\$(date) Installing Jupyter kernel"
              python -m ipykernel install --user --name daskpy3 --display-name "conda_daskpy3"
              source "$WORKING_DIR/miniconda/bin/deactivate"

              echo "\$(date) Signalling CloudFormation"
              curl -X PUT -H 'Content-Type:' \
                   --data-binary '{"Status":"SUCCESS","Reason":"Configuration Complete","UniqueId":"ID1","Data":"Notebook environment created"}' \
                   "${NotebookWaitHandle}"
              echo "\$(date) Finished!"
              EOF

              chown ec2-user:ec2-user /home/ec2-user/create.sh
              chmod +x /home/ec2-user/create.sh

              sudo -u ec2-user -i nohup /home/ec2-user/create.sh > /home/ec2-user/create-output.log 2>&1 &
      OnStart:
      - Content:
          Fn::Base64: |
            #!/bin/sh
            set -e
            WORKING_DIR=/home/ec2-user/SageMaker/custom-miniconda

            cat > /home/ec2-user/setup.sh << EOF
            #!/bin/bash

            echo "\$(date) Updating Jupyter config options"
            cp ~/.jupyter/jupyter_notebook_config.py ~/.jupyter/jupyter_notebook_config.py.bak
            echo "c.NotebookApp.iopub_data_rate_limit = 10000000000" >> ~/.jupyter/jupyter_notebook_config.py
            echo "c.NotebookApp.iopub_msg_rate_limit = 10000000000" >> ~/.jupyter/jupyter_notebook_config.py
            echo "c.EnvironmentKernelSpecManager.use_conda_directly = False" >> ~/.jupyter/jupyter_notebook_config.py
            rm /home/ec2-user/.condarc

            echo "\$(date) Re-installing Jupyter kernel"
            source "$WORKING_DIR/miniconda/bin/activate" daskpy3
            python -m ipykernel install --user --name daskpy3 --display-name "conda_daskpy3"
            source "$WORKING_DIR/miniconda/bin/deactivate"

            echo "\$(date) Finished!"
            EOF
            
            chown ec2-user:ec2-user /home/ec2-user/setup.sh
            chmod +x /home/ec2-user/setup.sh

            sudo -u ec2-user -i nohup /home/ec2-user/setup.sh >/home/ec2-user/setup-output.log 2>&1 &

  DaskNotebook:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      InstanceType: !Ref SagemakerNotebookInstance
      RoleArn:
        Fn::GetAtt:
          - SagemakerRole
          - Arn
      DefaultCodeRepository: !Ref SagemakerCodeRepo
      DirectInternetAccess: Enabled
      LifecycleConfigName:  !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
      PlatformIdentifier: notebook-al2-v2
      RootAccess: Enabled
      SecurityGroupIds:
        - Fn::GetAtt:
            - NotebookSecurityGroup
            - GroupId
      SubnetId:
        Ref: PublicSubnet1
      VolumeSizeInGB: 50

Outputs:
  JupyterNotebook:
      Value: !Join
      - ''
      - - https://
        - !Ref 'AWS::Region'
        - .console.aws.amazon.com/sagemaker/home?region=
        - !Ref 'AWS::Region'
        - '#/notebook-instances/openNotebook/'
        - !GetAtt 'DaskNotebook.NotebookInstanceName'
        - '?view=lab'
  DaskECSClusterName:
    Value: !Ref DaskCluster
