apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: pangeo
  version: "1.21"
  region: us-west-2

availabilityZones: ['us-west-2a','us-west-2b']

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
      labels: {aws-usage: "cluster-ops"}
    wellKnownPolicies:
      autoScaler: true
    roleName: eksctl-cluster-autoscaler-role
    roleOnly: true
  - metadata:
      name: ebs-csi-controller-sa
      namespace: kube-system
      labels:
        aws-usage: "cluster-ops"
        app.kubernetes.io/name: aws-ebs-csi-driver
    wellKnownPolicies:
      ebsCSIController: true
    roleName: ebs-csi-driver-role
    roleOnly: true

managedNodeGroups:
  - name: main
    minSize: 1
    maxSize: 10
    instanceTypes: ["m5.large", "m5.xlarge"]
    availabilityZones: ["us-west-2a"]
    privateNetworking: true
    volumeEncrypted: true
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
  - name: dask-workers
    minSize: 1
    maxSize: 30
    instanceTypes: ["m5.large", "m5.xlarge", "m5.2xlarge", "m5.4xlarge"]
    availabilityZones: ["us-west-2a"]
    privateNetworking: true
    volumeEncrypted: true
    spot: true
    taints:
    - key: lifecycle
      value: spot
      effect: NoExecute
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true

secretsEncryption:
  keyARN: <insert-your-kms-key-arn-here>
